server:
  port: 9090
  
  
  
spring:
  datasource:
    username: sa
    password: null
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    
    
    
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  

  mvc:
    view:
      prefix: /views/
      suffix: .jsp
      
      
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: anoop.emsl
    password: anp223939
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
